import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My To Do List App',
  description: 'Generated by create next app',
}
console.log(inter)
export default function RootLayout({ children }) {
  console.log(inter.className)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
