import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: '500' })

export const metadata = {
  title: 'My To Do List App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" name="theme-toggle" >
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
